services:
  hello-container:
    depends_on:
      - data-container
    image: nginx:1-alpine
    volumes:
      - scriptsdir:/home
    command: "/home/scripts/welcome-compose.sh"
  data-container:
    build:
      dockerfile: Dockerfile
    volumes:
      - scriptsdir:/home

volumes:
  scriptsdir: